#!/bin/bash -ex

ENV=install-test-env
[ ! -d $ENV ]
virtualenv -p python3 $ENV
. $ENV/bin/activate

PACKAGE=cookbook
REPO=Cookbook
UNINSTALL="pip uninstall --yes $PACKAGE"

# Install from git
pip install git+https://github.com/JohnReid/$REPO.git
python -c "import $PACKAGE"
$UNINSTALL

# Install from PyPI
pip install $PACKAGE
python -c "import $PACKAGE"
$UNINSTALL

# Install local version
python setup.py install
python -c "import $PACKAGE"
